# Generated by Django 4.0.4 on 2022-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=30)),
                ('babyname', models.CharField(max_length=40)),
                ('father', models.CharField(max_length=40)),
                ('mother', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=250)),
                ('birth', models.DateField(auto_now=True, verbose_name='birth')),
                ('pragnancyduration', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('cm_length', models.CharField(max_length=10)),
                ('kg_weight', models.CharField(max_length=10)),
                ('arrangement_among_siblings', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
