# Generated by Django 4.0.4 on 2022-04-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateTimeField(default=None, null=True, verbose_name='birth'),
        ),
    ]
