# Generated by Django 4.0.4 on 2022-04-25 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 4, 25, 4, 46, 53, 737641), null=True, verbose_name='birth'),
        ),
    ]
