# Generated by Django 4.0.4 on 2022-04-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birth',
        ),
    ]
