# Generated by Django 4.0.4 on 2022-05-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='bb', max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='arrangement_among_siblings',
            field=models.CharField(default='cc', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='babyname',
            field=models.CharField(default='bb', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='cm_length',
            field=models.CharField(default='cc', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='father',
            field=models.CharField(default='bb', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='cc', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='kg_weight',
            field=models.CharField(default='cc', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='mother',
            field=models.CharField(default='bb', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='2', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='pragnancyduration',
            field=models.CharField(default='cc', max_length=2),
        ),
    ]
