# Generated by Django 4.0.4 on 2022-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0015_remove_t_baby_remove_t_vaccine_delete_b_v_delete_t'),
        ('account', '0011_alter_account_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vaccine',
            field=models.ManyToManyField(to='vaccine.all_vaccines'),
        ),
    ]
