# Generated by Django 4.0.4 on 2022-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='vaccine',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='arrangement_among_siblings',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='babyname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='cm_length',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='father',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='kg_weight',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='mother',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='pragnancyduration',
            field=models.CharField(max_length=2),
        ),
    ]
