# Generated by Django 4.0.4 on 2022-05-12 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 5, 13), null=True, verbose_name='birth'),
        ),
    ]
