# Generated by Django 4.0.4 on 2022-05-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_account_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age_in_days',
            field=models.IntegerField(default=0, null=True, verbose_name='age in days'),
        ),
    ]
