# Generated by Django 4.0.4 on 2022-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_account_age_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age_in_days',
            field=models.IntegerField(default=None, null=True, verbose_name='age in days'),
        ),
    ]
