# Generated by Django 4.0.4 on 2022-05-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_myimagemodel_alter_account_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
