# Generated by Django 4.0.4 on 2022-05-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
