# Generated by Django 4.0.4 on 2022-07-19 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age_in_days',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='age in days'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 7, 19), null=True, verbose_name='birth'),
        ),
    ]
