# Generated by Django 4.0.4 on 2022-08-04 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_account_age_in_days_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 8, 4), null=True, verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
