# Generated by Django 4.0.4 on 2022-08-08 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_account_birth_alter_account_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 8, 8), null=True, verbose_name='birth'),
        ),
    ]
