# Generated by Django 4.0.4 on 2022-08-08 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_delete_myimagemodel_alter_account_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 8, 9), null=True, verbose_name='birth'),
        ),
    ]
