# Generated by Django 4.0.4 on 2022-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnesse',
            name='treat',
            field=models.ManyToManyField(to='app.treatment'),
        ),
    ]
