# Generated by Django 4.0.4 on 2022-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='food_icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
