# Generated by Django 4.0.4 on 2022-05-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feed_food_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='sleep_hours',
            new_name='sleep_duration',
        ),
    ]
