# Generated by Django 4.0.4 on 2022-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_sleep_hours_sleep_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='food_name',
            field=models.CharField(default='default food', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='food_type',
            field=models.CharField(default='default type', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='illnesse',
            name='ill_name',
            field=models.CharField(default='default ill', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lalluby',
            name='song_name',
            field=models.CharField(blank=True, default='default song', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_duration',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tip',
            field=models.TextField(default='default tip', max_length=2000),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treat_name',
            field=models.CharField(default='default treat', max_length=50, null=True),
        ),
    ]
