# Generated by Django 4.0.4 on 2022-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_feed_food_name_alter_feed_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lalluby',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
