# Generated by Django 4.0.4 on 2022-05-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_account_birth'),
        ('app', '0010_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='baby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
            preserve_default=False,
        ),
    ]
