# Generated by Django 4.0.4 on 2022-05-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_album_baby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='baby',
        ),
    ]
