# Generated by Django 4.0.4 on 2022-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_lalluby_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lalluby',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='audio'),
        ),
    ]
