# Generated by Django 4.0.4 on 2022-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_lalluby_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lalluby',
            name='song_name',
            field=models.CharField(blank=True, default='default song', max_length=100, null=True),
        ),
    ]
