# Generated by Django 4.0.4 on 2022-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lalluby_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='age_related',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
