# Generated by Django 4.0.4 on 2022-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tips_age_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='title',
            field=models.TextField(blank=True, default='default title', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tip',
            field=models.TextField(blank=True, default='default tip', max_length=2000, null=True),
        ),
    ]
