# Generated by Django 4.0.4 on 2022-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_feed_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='food_name',
            field=models.CharField(default='default food', max_length=100, null=True, verbose_name='food details'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_duration',
            field=models.CharField(blank=True, default='16', max_length=3, null=True),
        ),
    ]
