# Generated by Django 4.0.4 on 2022-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_feed_food_name_alter_sleep_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='sleep_duration',
            field=models.CharField(blank=True, default='15', max_length=3, null=True),
        ),
    ]
