# Generated by Django 4.0.4 on 2022-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_sleep_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='age_related',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='feed',
            name='food_type',
            field=models.CharField(choices=[('Breast milk', 'Breast milk'), ('Formula milk', 'Formula milk'), ('water', 'water'), ('fruits', 'fruits'), ('vegetables', 'vegetables'), ('cyrbohedats', 'cyrbohedats'), ('cremy', 'cremy')], default='default type', max_length=25, null=True),
        ),
    ]
