# Generated by Django 4.0.4 on 2022-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_feed_age_related_alter_feed_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='age_related',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
