# Generated by Django 4.0.4 on 2022-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_feed_age_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='age_related',
            field=models.IntegerField(default=1),
        ),
    ]
