# Generated by Django 4.0.4 on 2022-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_feed_food_type_alter_sleep_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='age_related',
            field=models.IntegerField(default=1, verbose_name='age related (in months)'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='sleep_duration',
            field=models.CharField(blank=True, default='15', max_length=8, null=True, verbose_name='sleep duration (in hours)'),
        ),
    ]
