# Generated by Django 4.0.4 on 2022-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_feed_age_related_alter_sleep_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='age_related',
            field=models.IntegerField(default=1, verbose_name='age related (in months)'),
        ),
    ]
