# Generated by Django 4.0.4 on 2022-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_sleep_age_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treat_name',
            field=models.CharField(default='default treat', max_length=300, null=True),
        ),
    ]
