# Generated by Django 4.0.4 on 2022-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_feed_age_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='food_type',
            field=models.CharField(choices=[('Breast milk', 'Breast milk'), ('Formula milk', 'Formula milk'), ('Water', 'Water'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Cyrbohedats', 'Cyrbohedats'), ('Cremy', 'Cremy')], default='default type', max_length=25, null=True),
        ),
    ]
