# Generated by Django 4.0.4 on 2022-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_feed_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='food_name',
            field=models.CharField(default='default food', max_length=300, null=True, verbose_name='food details'),
        ),
    ]
