# Generated by Django 4.0.4 on 2022-04-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('dose_num', models.PositiveSmallIntegerField(default=1)),
                ('taken', models.BooleanField(default=False)),
                ('static_duration', models.PositiveSmallIntegerField(default=30, verbose_name='static duration in days')),
                ('dead_line', models.DateTimeField(auto_now_add=True, verbose_name='date to take')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
