# Generated by Django 4.0.4 on 2022-04-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_alter_vaccine_static_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='dead_line',
            field=models.DateField(editable=False, verbose_name='date to take'),
        ),
    ]
