# Generated by Django 4.0.4 on 2022-04-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_alter_vaccine_dead_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
