# Generated by Django 4.0.4 on 2022-04-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_account_birth'),
        ('vaccine', '0005_delete_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('dose_num', models.PositiveSmallIntegerField(default=1)),
                ('taken', models.BooleanField(default=False)),
                ('static_duration', models.PositiveSmallIntegerField(default=1, verbose_name='static duration in monthes')),
                ('dead_line', models.DateField(editable=False, verbose_name='date to take')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
