# Generated by Django 4.0.4 on 2022-04-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_birth'),
        ('vaccine', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='baby',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='baby',
            field=models.ManyToManyField(to='account.account'),
        ),
    ]
