# Generated by Django 4.0.4 on 2022-04-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_birth'),
        ('vaccine', '0008_vaccine_details_remove_vaccine_dose_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacine_name', models.CharField(max_length=60, verbose_name='name')),
                ('dose_num', models.PositiveSmallIntegerField(default=1)),
                ('static_duration', models.PositiveSmallIntegerField(default=1, verbose_name='static duration in monthes')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='B_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('dead_line', models.DateField(editable=False, verbose_name='date to take')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.all_vaccines')),
            ],
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.DeleteModel(
            name='Vaccine_details',
        ),
    ]
