# Generated by Django 4.0.4 on 2022-04-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0009_all_vaccines_b_v_delete_vaccine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_vaccines',
            name='baby',
        ),
    ]
