# Generated by Django 4.0.4 on 2022-04-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0010_remove_all_vaccines_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_v',
            name='dead_line',
            field=models.DateField(default=None, editable=False, null=True, verbose_name='date to take'),
        ),
    ]
