# Generated by Django 4.0.4 on 2022-05-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0013_alter_t_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t',
            old_name='tryy',
            new_name='vaccine',
        ),
    ]
