# Generated by Django 4.0.4 on 2022-05-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_account_vaccine_alter_account_address_and_more'),
        ('vaccine', '0015_remove_t_baby_remove_t_vaccine_delete_b_v_delete_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('dead_line', models.DateField(default=None, editable=False, null=True, verbose_name='date to take')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.all_vaccines')),
            ],
        ),
    ]
